name: Build GearGlimpse
on:
  #  Workflow dispatch
  workflow_dispatch:

jobs:
  build:
    name: Build and upload GearGlimpse
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: "macos-latest"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Setup build environment
        run: make setup

      - name: Build GearGlimpse
        run: make build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Convert to IPA
        run: make ipa

      - name: Upload GearGlimpse.ipa Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GearGlimpse.ipa
          path: GearGlimpse.ipa
